services:
  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    ports:
      - '8108:8108'
    volumes:
      - ./typesense:${TYPESENSE_DATA_DIR}
    command: '--data-dir ${TYPESENSE_DATA_DIR} --api-key=${TYPESENSE_API_ADMIN_KEY} --enable-cors'
